workspace = { members = [ "capi/opencc_jieba_capi","tools/opencc-clip-jieba"] }
[package]
name = "opencc-jieba-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jieba-rs = "0.7.0"
regex = "1.10.4"
serde = { version = "1.0.198", features = ["derive"] }
serde_json = "1.0.116"
lazy_static = "1.4.0"
